CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin', 'user') DEFAULT 'user',
  tentativas_falhas INT DEFAULT 0,
  bloqueado_ate DATETIME NULL,
  criado_em DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS historico_senhas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  usuario_id INT NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS backup_agendamentos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cron_expressao VARCHAR(100) NOT NULL,
  descricao VARCHAR(255),
  ativo TINYINT(1) DEFAULT 1,
  ultimo_backup DATETIME NULL,
  criado_em DATETIME DEFAULT CURRENT_TIMESTAMP
);